spring.application.name=Notice

## H2 ?????? ?? (??/???)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:file:./data/myboard
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
# JPA(??????) ??
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true
#
#spring.sql.init.mode=never

# MySQL ?? ??
# localhost:3306/ ?? ?? ?? ? ??(myboard)? ????.
spring.datasource.url=jdbc:mysql://localhost:3306/myboard?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC

# ??? ? ?? ???(?? root)? ????
spring.datasource.username=root
spring.datasource.password=ring0627

# MySQL? ????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ??? ?? ?? ? ?? (update)
spring.jpa.hibernate.ddl-auto=update

# SQL ?? ??
spring.jpa.show-sql=true